[package]
name = "neon_async"
version = "0.1.0"
authors = ["Toshiya Nakakura <nakakura@me.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon_async"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.23"

[dependencies]
neon = "0.1.23"
